# Generated by Django 3.2 on 2021-05-14 17:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('role', models.TextField()),
                ('isAne', models.IntegerField()),
                ('isVol', models.IntegerField()),
                ('isPicth', models.IntegerField()),
                ('email', models.TextField()),
                ('telephone', models.TextField()),
                ('score', models.IntegerField()),
                ('loc', models.TextField()),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
