# Generated by Django 3.2 on 2021-05-14 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_api', '0002_auto_20210514_1736'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='User',
        ),
    ]
