# Generated by Django 3.2 on 2021-05-14 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_api', '0003_alter_user_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='isPicth',
            new_name='isPitch',
        ),
    ]
