# Generated by Django 3.2 on 2021-05-14 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_api', '0005_cas'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cas',
            table='Cas',
        ),
    ]
