# Generated by Django 3.2 on 2021-05-14 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_api', '0006_alter_cas_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.AddField(
            model_name='cas',
            name='role',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
