# Generated by Django 3.2 on 2021-05-14 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_api', '0007_auto_20210514_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cas',
            name='role',
            field=models.CharField(default='editor', max_length=20),
        ),
    ]
