# Generated by Django 3.2 on 2021-05-14 22:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('django_api', '0008_alter_cas_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ane',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('isFIni', models.BooleanField(default=0)),
                ('time', models.IntegerField(default=0)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Ane',
            },
        ),
    ]
