# Generated by Django 3.2 on 2021-05-17 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_api', '0011_auto_20210517_0450'),
    ]

    operations = [
        migrations.AddField(
            model_name='ane',
            name='comment',
            field=models.TextField(default='None'),
        ),
        migrations.AddField(
            model_name='pitch',
            name='comment',
            field=models.TextField(default='None'),
        ),
        migrations.AddField(
            model_name='vol',
            name='comment',
            field=models.TextField(default='None'),
        ),
    ]
