# Generated by Django 3.2 on 2021-05-17 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_api', '0012_auto_20210517_0801'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pays',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
