# Generated by Django 3.2 on 2021-05-18 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_api', '0013_user_pays'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ane',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anes', to='django_api.user'),
        ),
        migrations.AlterField(
            model_name='pitch',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pitchs', to='django_api.user'),
        ),
        migrations.AlterField(
            model_name='vol',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vols', to='django_api.user'),
        ),
    ]
