# Generated by Django 3.2 on 2021-05-18 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_api', '0014_auto_20210518_0331'),
    ]

    operations = [
        migrations.AddField(
            model_name='ane',
            name='user_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='anes', to='django_api.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pitch',
            name='user_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='pitchs', to='django_api.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vol',
            name='user_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='vols', to='django_api.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ane',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pitch',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='vol',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
