# Generated by Django 3.2 on 2021-05-18 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_api', '0015_auto_20210518_0337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ane',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='pitch',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='vol',
            name='user_id',
        ),
        migrations.AddField(
            model_name='ane',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='anes', to='django_api.user'),
        ),
        migrations.AddField(
            model_name='pitch',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='pitchs', to='django_api.user'),
        ),
        migrations.AddField(
            model_name='vol',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='vols', to='django_api.user'),
        ),
    ]
