# Generated by Django 3.2 on 2021-05-18 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_api', '0017_auto_20210518_0819'),
    ]

    operations = [
        migrations.AddField(
            model_name='pitch',
            name='isFini',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='pitch',
            name='isPart',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='vol',
            name='number',
            field=models.IntegerField(default=0),
        ),
    ]
