# Generated by Django 3.2 on 2021-05-18 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_api', '0019_vol_ispart'),
    ]

    operations = [
        migrations.AddField(
            model_name='pitch',
            name='number_2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pitch',
            name='number_3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pitch',
            name='number_4',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pitch',
            name='number_5',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pitch',
            name='number_6',
            field=models.IntegerField(default=0),
        ),
    ]
