# Generated by Django 3.2 on 2021-05-18 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_api', '0022_auto_20210518_1532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ane',
            name='stop_time',
        ),
    ]
