# Generated by Django 3.2 on 2021-05-18 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_api', '0023_remove_ane_stop_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='vol',
            name='isFreeze',
            field=models.BooleanField(default=0),
        ),
    ]
