# Generated by Django 3.2 on 2021-05-18 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_api', '0024_vol_isfreeze'),
    ]

    operations = [
        migrations.AddField(
            model_name='pitch',
            name='isFreeze',
            field=models.BooleanField(default=0),
        ),
    ]
