# Generated by Django 3.2 on 2021-06-13 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_api', '0026_category_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='dt_info',
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(default='Received', max_length=100, null=True),
        ),
    ]
