# Generated by Django 3.2 on 2021-06-13 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_api', '0029_alter_product_ttl_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='ttl_price',
        ),
    ]
