# Generated by Django 3.2 on 2021-06-19 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_api', '0030_remove_product_ttl_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, default='食品', max_length=200)),
            ],
            options={
                'verbose_name': 'fin_category',
                'verbose_name_plural': 'fin_categories',
                'db_table': 'FinCategory',
                'ordering': ('-name',),
            },
        ),
        migrations.CreateModel(
            name='Finance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('buyer', models.TextField(blank=True, default='', null=True)),
                ('price', models.FloatField()),
                ('facture', models.CharField(default='', max_length=100, null=True)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(default='食品', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='django_api.fincategory')),
            ],
            options={
                'db_table': 'Finance',
                'ordering': ('name',),
                'index_together': {('id',)},
            },
        ),
    ]
